checkpoints/latest:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${run.dir}/checkpoints/
  filename: latest
  every_n_epochs: 1

monitors/lr:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: epoch

checkpoints/best:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${run.dir}/checkpoints/
  filename: best
  monitor: val/losses/FINAL_LOSS
  mode: min
  every_n_epochs: 1
